# .air.toml
# Adjusted for project with main.go in cmd/main/

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main"
  bin = "tmp/main.exe"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
