// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteResponse struct {
	Success   bool   `json:"success"`
	DeletedID string `json:"deletedId"`
}

type Job struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	Location    string `json:"location"`
}

type Mutation struct {
}

type NewJob struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	Location    string `json:"location"`
}

type Query struct {
}
