# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/main"
bin = "tmp/main"
full_bin = ""
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
follow_symlink = true
log = "build-errors.log"
